services:
  postgres:
    image: postgres:15
    container_name: wedwise
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgress_pass
      POSTGRES_DB: db_wedwise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
